[package]
name = "rainbowgit"
version = "0.1.0"
edition = "2021"

[dependencies]
sha1 = "0.10"
flate2 = "1.0"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
